appname = casdoor
httpport = 8000
runmode = prod
copyrequestbody = true
driverName = postgres
dataSourceName = "${CASDOOR_DSN||user=casdoor password=change_me_strong host=db port=5432 sslmode=disable dbname=casdoor}"
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = ""
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
origin = "${RENDER_EXTERNAL_URL||http://localhost:8000}"
originFrontend =
enableErrorMask = false
inactiveTimeoutMinutes =
initDataFile = "${INIT_DATA_FILE||./init_data.json}"
